# Generated by Django 3.0.8 on 2021-01-01 16:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job_catalog', '0001_initial'),
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('program_id', models.CharField(db_index=True, max_length=100)),
                ('job_level', models.IntegerField()),
                ('hierarchy', models.CharField(blank=True, max_length=100, null=True)),
                ('work_location', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('currency', models.CharField(max_length=100)),
                ('min_rate', models.FloatField(blank=True, null=True)),
                ('max_rate', models.FloatField(blank=True, null=True)),
                ('min_rate_rule', models.CharField(choices=[('Can Change', 'Can Change'), ('Cannot Reduce', 'Cannot Reduce'), ('Cannot Change', 'Cannot Change')], default='Can Change', max_length=100)),
                ('max_rate_rule', models.CharField(choices=[('Can Change', 'Can Change'), ('Cannot Reduce', 'Cannot Reduce'), ('Cannot Change', 'Cannot Change')], default='Can Change', max_length=100)),
                ('unit_of_measure', models.CharField(blank=True, max_length=200, null=True)),
                ('job_category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='rate_card', to='job_catalog.JobCategory')),
                ('job_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='rate_card', to='job.Job')),
                ('job_title', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='rate_card', to='job_catalog.JobTitle')),
            ],
            options={
                'verbose_name': 'Rate Card',
                'verbose_name_plural': 'Rate Cards',
                'unique_together': {('program_id', 'job_category', 'job_title', 'job_level', 'job_template', 'hierarchy', 'work_location', 'region', 'currency')},
            },
        ),
    ]
