# Generated by Django 3.0.8 on 2021-02-05 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rate_card', '0003_auto_20210205_1545'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ratesofratecard',
            unique_together={('rate_card_id', 'unit_of_measure')},
        ),
    ]
