# Generated by Django 3.0.8 on 2021-01-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_distribution', '0002_vendorjobmapping_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorjobmapping',
            name='reason',
            field=models.CharField(blank=True, choices=[('', ''), ('cannot_service_this_category', 'Cannot Service This Category'), ('cannot_service_this_location', 'Cannot Service This Location'), ('cannot_service_this_position', 'Cannot Service This Position'), ('no_qualified_candidates_available', 'No Qualified Candidates Available'), ('supplier_can_later_come_back_and_opt-in_for_the_opted-out_job.', 'Supplier can later come back and opt-in for the opted-out job.')], default='', max_length=100, null=True),
        ),
    ]
