# Generated by Django 3.0.8 on 2021-01-19 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_distribution', '0003_auto_20210118_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorjobmapping',
            name='reason',
            field=models.CharField(blank=True, choices=[('', ''), ('Cannot Service This Category', 'Cannot Service This Category'), ('Cannot Service This Location', 'Cannot Service This Location'), ('Cannot Service This Position', 'Cannot Service This Position'), ('No Qualified Candidates Available', 'No Qualified Candidates Available'), ('Supplier can later come back and opt-in for the opted-out job', 'Supplier can later come back and opt-in for the opted-out job')], default='', max_length=100, null=True),
        ),
    ]
