# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: configurator.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='configurator.proto',
  package='Configurator',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x12\x63onfigurator.proto\x12\x0c\x43onfigurator\"(\n\x12ProgramInfoRequest\x12\x12\n\nprogram_id\x18\x01 \x01(\t\"\xea\x01\n\x13ProgramInfoResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x11\n\tclient_id\x18\x03 \x01(\t\x12\x0e\n\x06msp_id\x18\x04 \x01(\t\x12\x12\n\nvendor_ids\x18\x05 \x01(\t\x12\x12\n\nstart_date\x18\x06 \x01(\t\x12\x10\n\x08\x65nd_date\x18\x07 \x01(\t\x12\x12\n\nis_enabled\x18\x08 \x01(\x08\x12\x0e\n\x06\x63onfig\x18\t \x01(\t\x12\x0f\n\x07version\x18\n \x01(\x08\x12\x12\n\ncreated_on\x18\x0b \x01(\t\x12\x13\n\x0bmodified_on\x18\x0c \x01(\t2b\n\x07Program\x12W\n\x0egetProgramInfo\x12 .Configurator.ProgramInfoRequest\x1a!.Configurator.ProgramInfoResponse\"\x00\x62\x06proto3'
)




_PROGRAMINFOREQUEST = _descriptor.Descriptor(
  name='ProgramInfoRequest',
  full_name='Configurator.ProgramInfoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='program_id', full_name='Configurator.ProgramInfoRequest.program_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=76,
)


_PROGRAMINFORESPONSE = _descriptor.Descriptor(
  name='ProgramInfoResponse',
  full_name='Configurator.ProgramInfoResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Configurator.ProgramInfoResponse.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='Configurator.ProgramInfoResponse.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='client_id', full_name='Configurator.ProgramInfoResponse.client_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msp_id', full_name='Configurator.ProgramInfoResponse.msp_id', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vendor_ids', full_name='Configurator.ProgramInfoResponse.vendor_ids', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='start_date', full_name='Configurator.ProgramInfoResponse.start_date', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end_date', full_name='Configurator.ProgramInfoResponse.end_date', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_enabled', full_name='Configurator.ProgramInfoResponse.is_enabled', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='config', full_name='Configurator.ProgramInfoResponse.config', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='version', full_name='Configurator.ProgramInfoResponse.version', index=9,
      number=10, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='created_on', full_name='Configurator.ProgramInfoResponse.created_on', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='modified_on', full_name='Configurator.ProgramInfoResponse.modified_on', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=313,
)

DESCRIPTOR.message_types_by_name['ProgramInfoRequest'] = _PROGRAMINFOREQUEST
DESCRIPTOR.message_types_by_name['ProgramInfoResponse'] = _PROGRAMINFORESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ProgramInfoRequest = _reflection.GeneratedProtocolMessageType('ProgramInfoRequest', (_message.Message,), {
  'DESCRIPTOR' : _PROGRAMINFOREQUEST,
  '__module__' : 'configurator_pb2'
  # @@protoc_insertion_point(class_scope:Configurator.ProgramInfoRequest)
  })
_sym_db.RegisterMessage(ProgramInfoRequest)

ProgramInfoResponse = _reflection.GeneratedProtocolMessageType('ProgramInfoResponse', (_message.Message,), {
  'DESCRIPTOR' : _PROGRAMINFORESPONSE,
  '__module__' : 'configurator_pb2'
  # @@protoc_insertion_point(class_scope:Configurator.ProgramInfoResponse)
  })
_sym_db.RegisterMessage(ProgramInfoResponse)



_PROGRAM = _descriptor.ServiceDescriptor(
  name='Program',
  full_name='Configurator.Program',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=315,
  serialized_end=413,
  methods=[
  _descriptor.MethodDescriptor(
    name='getProgramInfo',
    full_name='Configurator.Program.getProgramInfo',
    index=0,
    containing_service=None,
    input_type=_PROGRAMINFOREQUEST,
    output_type=_PROGRAMINFORESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PROGRAM)

DESCRIPTOR.services_by_name['Program'] = _PROGRAM

# @@protoc_insertion_point(module_scope)
