# Generated by Django 3.0.8 on 2021-01-22 09:01

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaljob',
            name='after_immediate_distribution',
            field=django_mysql.models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='historicaljob',
            name='automatic_distribute_final_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaljob',
            name='automatic_distribute_submit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaljob',
            name='automatic_distribution',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaljob',
            name='distribute_schedule',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historicaljob',
            name='immediate_distribution',
            field=django_mysql.models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='historicaljob',
            name='manual_distribution_job_submit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaljob',
            name='submission_exceed_max_bill_rate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaljob',
            name='submission_limit_vendor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaljob',
            name='tiered_distribute_schedule',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='after_immediate_distribution',
            field=django_mysql.models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='automatic_distribute_final_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='automatic_distribute_submit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='automatic_distribution',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='distribute_schedule',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='immediate_distribution',
            field=django_mysql.models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='manual_distribution_job_submit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='submission_exceed_max_bill_rate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='submission_limit_vendor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='tiered_distribute_schedule',
            field=models.BooleanField(default=False),
        ),
    ]
