# Generated by Django 3.0.8 on 2021-02-05 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20210122_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaljob',
            name='job_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='job_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
