# Generated by Django 3.0.8 on 2021-02-08 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_auto_20210205_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaljob',
            name='source',
            field=models.CharField(choices=[('Template', 'Template'), ('CopyJob', 'CopyJob'), ('Catalog', 'Catalog')], default='Nothing', max_length=100),
        ),
        migrations.AddField(
            model_name='historicaljob',
            name='source_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='source',
            field=models.CharField(choices=[('Template', 'Template'), ('CopyJob', 'CopyJob'), ('Catalog', 'Catalog')], default='Nothing', max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='source_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
