# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: logger.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='logger.proto',
  package='Logger',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0clogger.proto\x12\x06Logger\"\xc0\x01\n\x0f\x41uditLogRequest\x12\x0f\n\x07program\x18\x01 \x01(\t\x12\x0c\n\x04user\x18\x02 \x01(\t\x12\x0e\n\x06source\x18\x03 \x01(\t\x12\n\n\x02ip\x18\x04 \x01(\t\x12\x12\n\nuser_agent\x18\x05 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x06 \x01(\t\x12\x13\n\x0brecord_type\x18\x07 \x01(\t\x12\x12\n\nrecord_ref\x18\x08 \x01(\t\x12\x11\n\tmeta_data\x18\t \x01(\t\x12\x12\n\ncreated_on\x18\n \x01(\x12\"\x1e\n\x10\x41uditLogResponse\x12\n\n\x02id\x18\x01 \x01(\t2M\n\x06Logger\x12\x43\n\x0csaveAuditLog\x12\x17.Logger.AuditLogRequest\x1a\x18.Logger.AuditLogResponse\"\x00\x62\x06proto3'
)




_AUDITLOGREQUEST = _descriptor.Descriptor(
  name='AuditLogRequest',
  full_name='Logger.AuditLogRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='program', full_name='Logger.AuditLogRequest.program', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user', full_name='Logger.AuditLogRequest.user', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='source', full_name='Logger.AuditLogRequest.source', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ip', full_name='Logger.AuditLogRequest.ip', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_agent', full_name='Logger.AuditLogRequest.user_agent', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='action', full_name='Logger.AuditLogRequest.action', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='record_type', full_name='Logger.AuditLogRequest.record_type', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='record_ref', full_name='Logger.AuditLogRequest.record_ref', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='meta_data', full_name='Logger.AuditLogRequest.meta_data', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='created_on', full_name='Logger.AuditLogRequest.created_on', index=9,
      number=10, type=18, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=217,
)


_AUDITLOGRESPONSE = _descriptor.Descriptor(
  name='AuditLogResponse',
  full_name='Logger.AuditLogResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Logger.AuditLogResponse.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=219,
  serialized_end=249,
)

DESCRIPTOR.message_types_by_name['AuditLogRequest'] = _AUDITLOGREQUEST
DESCRIPTOR.message_types_by_name['AuditLogResponse'] = _AUDITLOGRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AuditLogRequest = _reflection.GeneratedProtocolMessageType('AuditLogRequest', (_message.Message,), {
  'DESCRIPTOR' : _AUDITLOGREQUEST,
  '__module__' : 'logger_pb2'
  # @@protoc_insertion_point(class_scope:Logger.AuditLogRequest)
  })
_sym_db.RegisterMessage(AuditLogRequest)

AuditLogResponse = _reflection.GeneratedProtocolMessageType('AuditLogResponse', (_message.Message,), {
  'DESCRIPTOR' : _AUDITLOGRESPONSE,
  '__module__' : 'logger_pb2'
  # @@protoc_insertion_point(class_scope:Logger.AuditLogResponse)
  })
_sym_db.RegisterMessage(AuditLogResponse)



_LOGGER = _descriptor.ServiceDescriptor(
  name='Logger',
  full_name='Logger.Logger',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=251,
  serialized_end=328,
  methods=[
  _descriptor.MethodDescriptor(
    name='saveAuditLog',
    full_name='Logger.Logger.saveAuditLog',
    index=0,
    containing_service=None,
    input_type=_AUDITLOGREQUEST,
    output_type=_AUDITLOGRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_LOGGER)

DESCRIPTOR.services_by_name['Logger'] = _LOGGER

# @@protoc_insertion_point(module_scope)
