# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import logger_pb2 as logger__pb2


class LoggerStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.saveAuditLog = channel.unary_unary(
                '/Logger.Logger/saveAuditLog',
                request_serializer=logger__pb2.AuditLogRequest.SerializeToString,
                response_deserializer=logger__pb2.AuditLogResponse.FromString,
                )


class LoggerServicer(object):
    """Missing associated documentation comment in .proto file"""

    def saveAuditLog(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LoggerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'saveAuditLog': grpc.unary_unary_rpc_method_handler(
                    servicer.saveAuditLog,
                    request_deserializer=logger__pb2.AuditLogRequest.FromString,
                    response_serializer=logger__pb2.AuditLogResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Logger.Logger', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Logger(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def saveAuditLog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Logger.Logger/saveAuditLog',
            logger__pb2.AuditLogRequest.SerializeToString,
            logger__pb2.AuditLogResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
